### PR TITLE
Close the window when pressing the "esc" key

### PR DESCRIPTION
**Pull request by maxkueng**
This will close the current window when pressing the escape key. Except on Darwin this exits the app.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Just to verify: does this also close the application on other platforms? Changes look good though, thanks!

**Comment by maxkueng** [comment]
It's the same as pressing the [X] button on the window title. It closes the current window - on all platforms. [If it's the last window it will quit the app](https://github.com/yoshuawuyts/vmd/blob/a18d5cbd0e01218fccf4008697dd3a057d678cb9/server.js#L24-L26) except if `os.platform === 'darwin'` (OS X) which I assume is the standard behavior on OS X. But it doesn't close other windows. So it won't kill your other vmd windows if you happen to have multiple files open.

**Comment by yoshuawuyts** [comment]
:+1: let's merge it then!

**Comment by maxkueng** [comment]
Published a 1.2.0 since it's sort of a change in behavior.

**Pull request merged**
