### PR TITLE
bind ⌘W to close the window

### PR DESCRIPTION
**Pull request by gibatronic**
minor improvement to listen to ⌘W and close the window.

### CODE REVIEW

**Comment by Flet** [comment]
Cool idea! It might make sense to do this with electrons [global shortcut](https://github.com/atom/electron/blob/master/docs/api/global-shortcut.md) package in `server.js`.

**Comment by mattdesl** [comment]
Note with global shortcut, you need something like this to avoid it affecting other applications (at least on OS X). 

https://github.com/sindresorhus/electron-debug/blob/e5ae265a958b71d2a544ab3b0d093ff50e2b8d87/index.js#L26-L38

**Comment by maxkueng** [comment]
Electron's global shortcuts are actually global even when the app isn't focused, so something like in electron-debug needs to be done, like @mattdesl posted. But doing it like this seems a hacky to me. In electron-debug's case there seems to be no other option because it's sort of a "plugin" that's used during development and it can't inject itself in to the renderers. But it's not something you want to do if you have other options.

I think `⌘+W` (and `Control+W` too) should be handled in the renderer. 

BTW, the `Escape` key already closes the window. If that's not enough `⌘/Control+W` could be implemented the same way.

**Comment by gibatronic** [comment]
Perhaps the [global-shortcut](http://electron.atom.io/docs/v0.34.0/api/global-shortcut/) package is intended for shortcuts like ⌘Space for Spotlight, it really needs to be registered as a global shortcut.

I agree with @maxkueng that for ⌘W it suits better in the renderer.
I'll also include CTRL + W in this PR, sorry about that.

**Comment by Flet** [comment]
Cool, thanks for the insight!

**Comment by maxkueng** [comment]
@gibatronic It looks good so far. Do you want to add support for `Ctrl+W` too so it will also work on non-OSX operating systems? Then we can merge this.

**Comment by gibatronic** [comment]
Sure!

**Comment by maxkueng** [comment]
Thanks, mate! I've published your changes in vmd@1.12.0 :)

**Comment by gibatronic** [comment]
Awesome! :dancer:

**Pull request merged**
