### PR TITLE
If passed a directory, open its README.md file

### PR DESCRIPTION
**Pull request by josephfrazier**
This makes it easier to run, for example:

    vmd node_modules/electron

### CODE REVIEW

**Comment by mightyiam** [comment]
I would request documentation.

**Comment by josephfrazier** [comment]
Good point, @mightyiam! I just added https://github.com/yoshuawuyts/vmd/pull/94/commits/1f97fb44ce4f7874dd5164e2edee7760d58e43f3

**Comment by josephfrazier** [comment]
Nah, I'll pass on that :P There's currently no functionality tests in the repo anyway

**Comment by maxkueng** [comment]
Nice work! Thank you very much! I've published a new release with this feature.

**Comment by josephfrazier** [comment]
Cheers for the quick merge/release, @maxkueng!

**Pull request merged**
