### PR TITLE
Upgrade electron to get rid of SEGFAULT

### PR DESCRIPTION
**Pull request by ralphtheninja**
Closes https://github.com/yoshuawuyts/vmd/issues/126

Crashes on Ubuntu 18.10 as well.

### CODE REVIEW

**Comment by maxkueng** [comment]
Thanks! After I tested your branch I want ahead Upgraded to Electron 3.0.9. Everything seems to work. I hope they didn't introduce a new segfault.

**Comment by ralphtheninja** [comment]
> Thanks! After I tested your branch I want ahead Upgraded to Electron 3.0.9. Everything seems to work. I hope they didn't introduce a new segfault.

Might not be a good idea to upgrade to 3. I know @substack had problems on Debian. But I guess we will see :)

**Comment by maxkueng** [comment]
Do you know what kind of problems he had? I tested every vmd feature on Manjaro with Electron 3 and it worked fine. It's the only way I test before a release as I don't have any other machines that run other operating systems. And we don't have any automated tests. 

Let me know if you encounter issues on your machine(s). In the worst case I'll downgrade.

Thanks for the PR, by the way!

**Comment by ralphtheninja** [comment]
> Do you know what kind of problems he had?

It was on the `deltachat-desktop` application. The window just didn't show up at all.

**Pull request merged**
