### PR TITLE
Change app menu and add print function

### PR DESCRIPTION
**Pull request by waynezhang**
Change app menu and add print function

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
I like this addition. Can you make sure the tests pass? `standard` is failing. Thanks!

**Comment by waynezhang** [comment]
@yoshuawuyts fixed that.

**Comment by yoshuawuyts** [comment]
Merged in cc132e0

**Comment by yoshuawuyts** [comment]
released as `vmd@1.6.0`

**Pull request closed without merging**
