### PR TITLE
Add stdin support

### LINKED ISSUE #18: pipe stdin to vmd
e.g. be able to do this:
```sh
cat README.md | vmd
```

Doesn't make `vmd` a pager yet, but does allow for more unixy actions. Also maybe detect if in TTY to pipe to stdout. Not sure what the added value would be over something like `cat`, but playing ball with cli tools is a good thing imo.

```sh
vmd README.md | grep -C 3 foo > file.md
```

### PR DESCRIPTION
**Pull request by noffle**
Built atop @mattdesl's work on #28 to fix #18. I added a bit of code that has the CLI process bail if stdin is a TTY (i.e. nothing is being piped in). Oh, and a trivial bit of whitespace that was making `standard` balk.

### CODE REVIEW

**Comment by mattdesl** [comment]
LGTM. I can add readme docs as well. 

@maxkueng What do you think?

**Comment by maxkueng** [comment]
There is a problem with relative image paths when the document comes from `stdin` and the referenced image paths are not in the current directory.

Take vmd's README.md, for example.

This shows the screenshot:

```sh
cat README.md | ./bin/cli.js
```

But this doesn't work:

```sh
cd docs
cat ../README.md | ../bin/cli.js
```

The following ist still okay and works:

```sh
cd docs
../bin/cli.js ../README.md 
```

I'm not sure if it's even possible to find the correct base path when a document is piped in. But it breaks images and relative links to other markdown documents (which we will hopefully support in the future).

Other than that it looks good to me. Great work!

**Comment by maxkueng** [comment]
I think it's okay like that though. I don't see how this could be made to work otherwise. So if you want to read from `stdin` and want relative paths to work you just have to `cd` to the right directory.

@mattdesl: Want to merge it? LGTM

**Comment by mattdesl** [comment]
Yeah I can't think of any way of fixing that. :disappointed: 

Ok, I can merge it in and release a minor version.

**Comment by maxkueng** [comment]
Update the README first. Yeah, minor version bump. Can you publish to npm too?

**Comment by mattdesl** [comment]
Right, will do readme first. Cheers

**Comment by mattdesl** [comment]
I am kinda newb with travis; it seems like opening a new branch will break the main build status listed in the badge? 

Anyways I will be careful to work in my fork for new branches.

**Comment by maxkueng** [comment]
> it seems like opening a new branch will break the main build status listed in the badge?

Uh no, it shouldn't.

**Comment by mattdesl** [comment]
Not too sure why the badge is saying `failing` since the current / last commit succeeded. 

screen shot 2015-07-07 at 2 28 27 pm

**Comment by maxkueng** [comment]
@mattdesl: Yeah, I see it. But it says `sh: 1: standard: not found`. Looks like it couldn't install the `standard` module. Maybe it was just a glitch. I'm re-running it.

**Comment by maxkueng** [comment]
@mattdesl: [All green now](https://travis-ci.org/yoshuawuyts/vmd/builds/69911548)

**Pull request merged**
