### PR TITLE
Change key modifiers to CmdOrCtrl

### LINKED ISSUE #37: Keyboard shortcuts don't work on Linux
for example `q` does not quit app, but `ESC` does work. :smile:

### PR DESCRIPTION
**Pull request by xHN35RQ**
This allows VMD keyboard shortcuts to work on Linux and Windows. Fixes #37

### CODE REVIEW

**Comment by Flet** [comment]
NIce :+1:

**Comment by maxkueng** [comment]
It's on npm! thanks

**Comment by xHN35RQ** [comment]
nice, thanks. :+1:

**Comment by xHN35RQ** [comment]
@maxkueng quick question: why does VMD re-download electron-prebuilt every single time I update from npm?

**Comment by maxkueng** [comment]
@xHN35RQ Probably because we're using `electron-prebuilt@0.24.0` which doesn't cache the downloaded electron releases. This might be fixed in the current version. electron-prebuilt uses electron-download which downloads Electron releases. According to the docs the current version of electron-download by default caches downloads in `~/.electron`.

So we might just have to upgrade to a later version of electron-prebuilt and hope everything still works. If you have time you can try it out and submit a PR.

**Pull request merged**
